# https://support.crowdin.com/configuration-file/

# Crowdin's credentials
"project_identifier" : "adblockplusui"
# Required for passing environment variable via `crowdin -k CROWDIN_API_KEY`
"api_key_env" : CROWDIN_API_KEY

# Translation strings location
"base_path" : "./locale"

# If true folder structures(i.e.: `/en_US/common.json`) will be added to Crowdin
"preserve_hierarchy": false

# Files configuration
"files": [
  {
    "ignore": ["/en_US/updates-latest.json"],
    "source" : "/en_US/*.json",
    "translation" : "/%two_letters_code%/%original_file_name%"
  }
]
